# ############################################################################
# ## WDOSX DOS Extender           Copyright (c) 1996, 1999, Michael Tippach ##
# ##                                                                        ##
# ## Released under the terms of the WDOSX license agreement.               ##
# ############################################################################
#
# $Header: E:/RCS/wdosx/0.95/src/util/makefile 1.6 1999/06/20 15:52:43 MikeT Exp $
#
# ----------------------------------------------------------------------------
#
# $Log: makefile $
# Revision 1.6  1999/06/20 15:52:43  MikeT
# Use Joergen Ibsen's WPACK compressor instead of the old LZ77 one.
#
# Revision 1.5  1999/02/07 18:29:52  MikeT
# Legacy directory is now being build and not just the binaries pulled
# from there.
#
# Revision 1.4  1999/02/06 19:57:33  MikeT
# Get the makefile for the Win32 directory first, before using it...
#
# Revision 1.3  1999/02/06 19:50:14  MikeT
# Also create ..\kernel directory on GET.
#
# Revision 1.2  1999/02/06 19:48:57  MikeT
# Create source directories if not already there.
#
# Revision 1.1  1999/02/06 19:29:49  MikeT
# Initial check in.
#
#
# ----------------------------------------------------------------------------
#
# Makefile for stubit.exe
#
ASM = tasm.exe
AFLAGS = /m9 /mx
CC = bcc32.exe
CCFLAGS = -O2 -5
CO = coo.exe

makefile : stubit.exe

stubit.exe : si.exe ..\win32\kernel32.wdl ..\win32\user32.wdl
    COPY ..\win32\kernel32.wdl
    COPY ..\win32\user32.wdl
    COPY si.exe stubit.exe
    stubit si.exe
    si stubit.exe

..\win32\kernel32.wdl :
    CD ..\win32
    make kernel32.wdl
    CD ..\util

..\win32\user32.wdl :
    CD ..\win32
    make user32.wdl
    CD ..\util

si.exe : dosext.h load_hll.h load_cof.h load_asm.h load_le.h load_rdf.h \
             load_pe0.h load_d32.h stubit.c addfile.obj import.obj \
             ..\wpack\wpack.obj
    $(CC) $(CCFLAGS) -esi.exe stubit.c addfile.obj import.obj ..\wpack\wpack.obj

..\wpack\wpack.obj :
    cd ..\wpack
    make wpack.obj
    cd ..\util

addfile.obj : addfile.asm

import.obj : import.asm

dosext.h : ..\kernel\wdosx.dx
    ..\hacks\toh ..\kernel\wdosx.dx dosext.h wdosx_bin

..\kernel\wdosx.dx :
    CD ..\kernel
    make wdosx.dx
    CD ..\util

load_hll.h : ..\legacy\loadpe.win
    ..\hacks\toh ..\legacy\loadpe.win load_hll.h winPE_bin

..\legacy\loadpe.win :
    CD ..\legacy
    make loadpe.win
    CD ..\util

load_cof.h : ..\coff\stubc.cof
    ..\hacks\toh ..\coff\stubc.cof load_cof.h coff_bin

..\coff\stubc.cof :
    CD ..\coff
    make stubc.cof
    CD ..\util

load_asm.h : ..\legacy\loadpe.raw
    ..\hacks\toh ..\legacy\loadpe.raw load_asm.h rawPE_bin

..\legacy\loadpe.raw :
    CD ..\legacy
    make loadpe.raw
    CD ..\util

load_le.h : ..\kernel\wdosxle.exe
    ..\hacks\toh ..\kernel\wdosxle.exe load_le.h LE_bin

..\kernel\wdosxle.exe :
    CD ..\kernel
    make wdosxle.exe
    CD ..\util

load_rdf.h : ..\rdoff\rdoff.rd
    ..\hacks\toh ..\rdoff\rdoff.rd load_rdf.h rdfload_bin

..\rdoff\rdoff.rd :
    CD ..\rdoff
    make rdoff.rd
    CD ..\util

load_pe0.h : ..\pe\loadpe.ra0
    ..\hacks\toh ..\pe\loadpe.ra0 load_pe0.h peload_ra0

..\pe\loadpe.ra0 :
    CD ..\pe
    make loadpe.ra0
    CD ..\util

load_d32.h : ..\dos32\wdx32dx
    ..\hacks\toh ..\dos32\wdx32.dx load_d32.h dos32_bin

..\dos32\wdx32dx :
    CD ..\dos32
    make wdx32.dx
    CD ..\util

.asm.obj :
    $(ASM) $(AFLAGS) $<

get :
    $(CO) ADDFILE.ASM
    $(CO) GENERAL.INC
    $(CO) WDXINFO.INC
    $(CO) DUALMODE.INC
    $(CO) W32STRUC.INC
    $(CO) IMPORT.ASM
    $(CO) STUBIT.C
    $(CO) WDXINFO.H
    MD ..\dos32
    CD ..\dos32
    $(CO) makefile
    make get
    MD ..\rdoff
    CD ..\rdoff
    $(CO) makefile
    make get
    MD ..\pe
    CD ..\pe
    $(CO) makefile
    make get
    MD ..\coff
    CD ..\coff
    $(CO) makefile
    make get
    MD ..\kernel
    CD ..\kernel
    $(CO) makefile
    make get
    MD ..\win32
    CD ..\win32
    $(CO) makefile
    make get
    MD ..\legacy
    CD ..\legacy
    $(CO) makefile
    make get
    MD ..\wpack
    CD ..\wpack
    $(CO) makefile
    make get
    CD ..\util

clean :
    DEL dosext.h
    DEL load_hll.h
    DEL load_cof.h
    DEL load_asm.h
    DEL load_le.h
    DEL load_rdf.h
    DEL load_pe0.h
    DEL load_d32.h
    DEL *.obj
    DEL *.exe
    DEL *.map
    DEL *.wdl
    DEL *.bak
    CD ..\dos32
    make clean
    CD ..\rdoff
    make clean
    CD ..\pe
    make clean
    CD ..\coff
    make clean
    CD ..\kernel
    make clean
    CD ..\win32
    make clean
    CD ..\legacy
    make clean
    CD ..\wpack
    make clean
    CD ..\util
