{                    GNU LESSER GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

 Full text of license:
 https://www.gnu.org/licenses/lgpl-3.0.en.html

 (c) Copyright 2022 DosWord
 (c) Copyright 1997-1998 Iggor Khachko - hachko@icl.kazan.su }

procedure ChDir( const Dir: String);
procedure MkDir( const Dir: String);
procedure RmDir( const Dir: String);
procedure GetDir( Drive: Byte; var Dir: String);
