{                    GNU LESSER GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

 Full text of license:
 https://www.gnu.org/licenses/lgpl-3.0.en.html

 (c) Copyright 2022 DosWord
 (c) Copyright 1997-1998 Iggor Khachko - hachko@icl.kazan.su }

function Trunc(R: Extended): LongInt;
function Round( R: Extended): LongInt;
function Int( R: Extended): Extended;
function Frac( R: Extended): Extended;
function Exp( R: Extended): Extended;
function Ln( R: Extended): Extended;
