# ############################################################################
# ## WDOSX DOS Extender           Copyright (c) 1996, 1999, Michael Tippach ##
# ##                                                                        ##
# ## Released under the terms of the WDOSX license agreement.               ##
# ############################################################################
#
# $Header: E:/RCS/wdosx/0.95/src/build.me/makefile 1.2 2000/05/28 12:39:35 MikeT Exp $
#
# ----------------------------------------------------------------------------
#
# $Log: makefile $
# Revision 1.2  2000/05/28 12:39:35  MikeT
# Add wdmem utility.
#
# Revision 1.1  1999/02/07 20:47:22  MikeT
# Initial check in.
#
#
# ----------------------------------------------------------------------------
#
# Build all the WDOSX binaries
#

CO = coo.exe

makefile : stubit.exe wudebug.exe wadd.exe wdir.exe kernel32.wdl user32.wdl \
           oleaut32.wdl advapi32.wdl wdmem.exe

stubit.exe : ..\util\stubit.exe
    COPY ..\util\stubit.exe

wudebug.exe : ..\deb\wudebug.exe
    COPY ..\deb\wudebug.exe

wadd.exe : ..\tools\wadd.exe
    COPY ..\tools\wadd.exe
 
wdir.exe : ..\tools\wdir.exe
    COPY ..\tools\wdir.exe

wdmem.exe : ..\tools\wdmem.exe
    COPY ..\tools\wdmem.exe

kernel32.wdl : ..\win32\kernel32.wdl
    COPY ..\win32\kernel32.wdl

user32.wdl : ..\win32\user32.wdl
    COPY ..\win32\user32.wdl

oleaut32.wdl : ..\win32\oleaut32.wdl
    COPY ..\win32\oleaut32.wdl

advapi32.wdl : ..\win32\advapi32.wdl
    COPY ..\win32\advapi32.wdl


..\util\stubit.exe :
    CD ..\util
    make stubit.exe
    CD ..\build.me

..\deb\wudebug.exe :
    CD ..\deb
    make wudebug.exe
    CD ..\build.me

..\tools\wadd.exe :
    CD ..\tools
    make wadd.exe
    CD ..\build.me

..\tools\wdir.exe :
    CD ..\tools
    make wdir.exe
    CD ..\build.me

..\tools\wdmem.exe :
    CD ..\tools
    make wdmem.exe
    CD ..\build.me

..\win32\kernel32.wdl :
    CD ..\win32
    make kernel32.wdl
    CD ..\build.me

..\win32\user32.wdl :
    CD ..\win32
    make user32.wdl
    CD ..\build.me

..\win32\oleaut32.wdl :
    CD ..\win32
    make oleaut32.wdl
    CD ..\build.me

..\win32\advapi32.wdl :
    CD ..\win32
    make advapi32.wdl
    CD ..\build.me

get :
    MD ..\win32
    CD ..\win32
    $(CO) makefile
    make get
    MD ..\util
    CD ..\util
    $(CO) makefile
    make get
    MD ..\tools
    CD ..\tools
    $(CO) makefile
    make get
    MD ..\deb
    CD ..\deb
    $(CO) makefile
    make get
    CD ..\build.me

clean :
    CD ..\util
    make clean
    CD ..\win32
    make clean
    CD ..\tools
    make clean
    CD ..\deb
    make clean
    CD ..\build.me
    DEL *.exe
    DEL *.wdl
